fx_version 'cerulean'
game 'gta5'

lua54 'yes'

name 'craft3d'
description 'Table de craft 3D pour ESX'
author 'Generated by ChatGPT'
version '1.0.0'

ui_page 'ui/index.html'

shared_scripts {
    'config.lua'
}

client_scripts {
    'client/main.lua'
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'server/main.lua'
}

files {
    'ui/index.html',
    'ui/style.css',
    'ui/script.js'
}
